import os
os.system ("clear")
os.system ("pkg update -y")
os.system ("pkg upgrade -y")
os.system ("pkg install python -y")
os.system (" pkg install python2 -y")
os.system ("pkg install python2-dev -y")
os.system ("pkg install python3 -y")
os.system ("pkg install java -y")
os.system (" pkg install ruby -y")
os.system ("pkg install help -y")
os.system ("pkg install git -y")
os.system ("pkg install git -y")
os.system ("pkg install host -y")
os.system ("pkg install php -y")
os.system ("pkg install perl -y")
os.system (" install nmap -y")
os.system (" pkg install bash -y")
os.system ("pkg install clang -y")
os.system (" pkg install nano -y")
os.system (" pkg install w3m -y")
os.system (" install havij -y")
os.system ("pkg install hydra -y ")
os.system (" pkg install figlet -y ")
os.system (" pkg install cowsay -y ")
os.system (" pkg install curl -y ")
os.system (" pkg install tar -y ")
os.system (" pkg install zip -y ")
os.system (" pkg install unzip -y ")
os.system (" pkg install tor -y ")
os.system (" pkg install google -y ")
os.system (" pkg install sudo -y ")
os.system (" pkg install wget -y ")
os.system (" pkg install wireshark -y ")
os.system (" pkg install wgetrc -y ")
os.system ("pkg install wcalc -y ")
os.system (" pkg install bmon -y ")
os.system (" pkg install vpn -y ")
os.system (" pkg install unrar -y ")
os.system (" pkg install toilet -y ")
os.system (" pkg install proot -y ")
os.system (" pkg install net-tools -y ")
os.system (" pkg install golang -y ")
os.system (" pkg install chroot -y ")
os.system (" termux-chroot -y")
os.system (" pkg install macchanger -y ")
os.system (" pkg install openssl -y ")
os.system (" pkg install cmatrix -y ")
os.system (" pkg install openssh -y ")
os.system (" pkg install wireshark -y ")
os.system (" termux-setup-storage -y")
os.system (" pkg install macchanger -y ")
os.system (" apt update && apt upgrade -y ")
os.system (" cd ")
os.system ("git clone https://github.com/verluchie/termux-metasploit.git")
os.system ("cd termux-metasploit")
os.system (" chmod 777 install.sh")
os.system ("sh install.sh")
import os
os.system ("clear")
print("|||   ||| |||||||")
print("|||   |||   |||")
print("|||||||||   |||")
print("|||   |||   |||")
print("|||   ||| |||||||")
print ("")
print("|||||||  |||")
print("  |||    |||||||||")
print("  |||    |||   |||")
print("  |||    |||   |||")
print("|||||||  |||   |||")
print("")
print("__    __  _____   _   _   __   _   _____   _____   _____         _   _       ___   _____   _   _    _____   _____    _____  ") 
print("\ \  / / /  _  \ | | | | |  \ | | /  ___| | ____| |  _  \       | | | |     /   | /  ___| | | / /  | ____| |  _  \  /  ___/ ")
print(" \ \/ /  | | | | | | | | |   \| | | |     | |__   | |_| |       | |_| |    / /| | | |     | |/ /   | |__   | |_| |  | |___  ")
print("  \  /   | | | | | | | | | |\   | | |  _  |  __|  |  _  /  ___  |  _  |   / / | | | |     | |\ \   |  __|  |  _  /  \___  \ ")
print("  / /    | |_| | | |_| | | | \  | | |_| | | |___  | | \ \       | | | |  / /  | | | |___  | | \ \  | |___  | | \ \   ___| | ") 
print(" /_/     \_____/ \_____/ |_|  \_| \_____/ |_____| |_|  \_\      |_| |_| /_/   |_| \_____| |_|  \_\ |_____| |_|  \_\ /_____/ ") 
