import os
os.system ("clear")
os.system ("pkg update -y")
os.system ("pkg upgrade -y")
os.system ("pkg install python -y")
os.system (" pkg install python2 -y")
os.system ("pkg install python2-dev -y")
os.system ("pkg install python3 -y")
os.system ("pkg install java -y")
os.system (" pkg install ruby -y")
os.system ("pkg install help -y")
os.system ("pkg install git -y")
os.system ("pkg install git -y")
os.system ("pkg install host -y")
os.system ("pkg install php -y")
os.system ("pkg install perl -y")
os.system (" install nmap -y")
os.system (" pkg install bash -y")
os.system ("pkg install clang -y")
os.system (" pkg install nano -y")
os.system (" pkg install w3m -y")
os.system (" install havij -y")
os.system ("pkg install hydra -y ")
os.system (" pkg install figlet -y ")
os.system (" pkg install cowsay -y ")
os.system (" pkg install curl -y ")
os.system (" pkg install tar -y ")
os.system (" pkg install zip -y ")
os.system (" pkg install unzip -y ")
os.system (" pkg install tor -y ")
os.system (" pkg install google -y ")
os.system (" pkg install sudo -y ")
os.system (" pkg install wget -y ")
os.system (" pkg install wireshark -y ")
os.system (" pkg install wgetrc -y ")
os.system ("pkg install wcalc -y ")
os.system (" pkg install bmon -y ")
os.system (" pkg install vpn -y ")
os.system (" pkg install unrar -yl ")
os.system (" pkg install toilet -y ")
os.system (" pkg install proot -y ")
os.system (" pkg install net-tools -y ")
os.system (" pkg install golang -y ")
os.system (" pkg install chroot -y ")
os.system (" termux-chroot -y")
os.system (" pkg install macchanger -y ")
os.system (" pkg install openssl -y ")
os.system (" pkg install cmatrix -y ")
os.system (" pkg install openssh -y ")
os.system (" pkg install wireshark -y ")
os.system (" termux-setup-storage -y")
os.system (" pkg install macchanger -y ")
os.system (" apt  && apt upgrade -y ")
os.system ("clear")
os.system ("apt update  ")
os.system ("apt upgrade ")
os.system ("apt install update ")
os.system ("apt install upgrade ")
os.system ("termux-setup-storage ")
os.system ("apt-get update ")
os.system ("apt-get upgrade ")
os.system ("apt install php ")
os.system ("apt install python ")
os.system ("apt install python2 ")
os.system ("apt install git ")
os.system ("apt install golang ")
os.system ("apt install host  ")
os.system ("apt install nano ")
os.system ("apt install havij  ")
os.system ("apt install hydra ")
os.system ("apt install wireshark  ")
os.system ("apt install cmatrix ")
os.system ("apt install figlet ")
os.system ("apt install wget ")
os.system ("apt install wget -y ")
os.system ("apt install python2 -y ")
os.system ("apt install python2-dev -y ")
os.system ("apt install wireshark  ")
os.system ("apt install cowsay")
os.system ("apt install toilet ")
os.system ("apt install ruby ")
os.system ("apt install help  ")
os.system ("apt gem install lolcat ")
os.system ("apt install curl ")
os.system ("apt install wgetrc  ")
os.system ("apt install unzip ")
os.system ("apt install openssh ")
os.system ("apt install tor ")
os.system ("apt install uzip ")
os.system ("apt install net-tools ")
os.system ("apt install unrar ")
os.system ("apt install clang ")
os.system ("apt install w3m ")
os.system ("apt install proot ")
os.system ("pip2 install wget ")
os.system ("pip2 install requests ")
os.system ("apt update && apt upgrade ")
os.system ("clear")
